# Generated by Django 4.1.1 on 2022-12-12 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                ("problem_id", models.IntegerField(primary_key=True, serialize=False)),
                ("problem_name", models.CharField(max_length=100)),
                ("problem_content", models.TextField(default="")),
                ("problem_restrictions", models.TextField(default="")),
                ("skeleton_code", models.TextField(default="")),
                ("answer", models.TextField(default="")),
                ("due_date", models.DateTimeField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="UnitTest",
            fields=[
                ("test_id", models.IntegerField(primary_key=True, serialize=False)),
                ("test_content", models.TextField(default="")),
                ("test_answer", models.TextField(default="")),
                (
                    "problem_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.problem"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Completed",
            fields=[
                (
                    "completed_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("metric", models.IntegerField(default="")),
                ("copy", models.IntegerField(default="")),
                ("readability", models.IntegerField(default="")),
                ("score", models.IntegerField(default="")),
                (
                    "problem_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.problem"
                    ),
                ),
            ],
        ),
    ]
